name: Docker Image CI

on:
  #push:
  #  branches: [ "${{ github.repository }}" ]
  #pull_request:
  #  branches: [ "${{ github.repository }}" ]
  workflow_dispatch:
  #  branches: [ "${{ github.repository }}" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - run: echo "Deploying to production server on branch $GITHUB_REF"
    - run: echo "Deploying to production server on branch "${{ github.repository }}""

    - name: Checkout the default branch 
      uses: actions/checkout@v3

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag ${{ github.repository }}:${{ github.run_id }}

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        #registry: hub.docker.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ github.repository }}:${{ github.run_id }}
      
 


  Analysis:
    runs-on: ubuntu-latest

    steps:
       - run: echo "Analizing the code"
       - run: echo "It is a test job"

  
  Development:
    name: Deploy to Dev
    permissions:
      contents: none 
    runs-on: ubuntu-latest
    needs: [ build, Analysis]
    environment:
      name: "Development"
    #   url: ${ { steps.deploy-to-webapp.outputs.webapp-url } }

    steps:
      - run: echo "Deploy into Dev enviro"
      - run: echo "This is deployment  job"
  
  Staging:
    name: Deploy to Stg
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: Development
    environment:
      name: "Staging"
    #   url: ${ { steps.deploy-to-webapp.outputs.webapp-url } }

    steps:
      - run: echo "Deploy into STG enviro"
      - run: echo "This is deployment  job"
  
  Production:
    name: Deploy to Production
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: Staging
    environment:
      name: "Production"
    #   url: ${ { steps.deploy-to-webapp.outputs.webapp-url } }

    steps:
      - run: echo "Deploy into PROD enviro"
      - run: echo "This is deployment  job"
  
  DR:
    name: Deploy to DR
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: ['Staging']
    environment:
      name: "DR"
    #   url: ${ { steps.deploy-to-webapp.outputs.webapp-url } }

    steps:
      - run: echo "Deploy into DR enviro"
      - run: echo "This is deployment  job"
  