name: Docker Image CI

on:
  push:
    branches: [ "${{ github.repository }}" ]
  pull_request:
    branches: [ "${{ github.repository }}" ]
  workflow_dispatch:
    branches: [ "${{ github.repository }}" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - run: echo "Deploying to production server on branch $GITHUB_REF"
    - run: echo "Deploying to production server on branch "${{ github.repository }}"

    - name: Checkout the default branch 
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ github.repository }}:${{ github.run_id }}

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        #registry: hub.docker.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
