# This is a basic workflow to help you get started with Actions

name: rg-creation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - '/UtilityCollection/infra/*.tf'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  resourcegroups:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    name: 'rg-creation'
    env:
      # CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      # CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      # SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION  }}
      # TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKINGDIR: 'UtilityCollection/infra'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: 'Working Directory'
        run: cd ${{ WORKINGDIR }}
      
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Runs a single command using the runners shell
      - name: 'Terraform init'
        id: init
        run: |
          
          terraform init          

      - name: 'Terraform plan'
        id: plan
        run: |
          
          terraform plan
                    
      - name: 'Terraform apply'
        id: apply
        run: |
          
          terraform apply -auto-approve          
